# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TiSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'TillusorySDK', :path => '../'
#  pod 'Masonry'
#  pod 'SSZipArchive'
  
end
